export const API_ENDPOINTS = {
  DASHBOARD: '/home',
  PRODUCTS: '/products',
  USERS: '/users',
  EXPENSES: '/expenses',
  CATEGORIES: '/categories',
  BRANDS: '/brands',
  EXPORT_CATEGORIES: '/categories/export',
  IMPORT_CATEGORIES: '/categories/import',
  CATEGORY_TEMPLATE: '/categories/template',
  EXPORT_BRANDS: '/brands/export',
  IMPORT_BRANDS: '/brands/import',
  BRAND_TEMPLATE: '/brands/template',
  TAGS: '/tags', // Added Tags endpoint
  ORDERS: '/orders',
  VOUCHERS: '/vouchers',
  BLOGS: '/blogs',
  REVIEWS: '/reviews',
  SHIPPING_ADDRESSES: '/shipping-addresses',
  PRODUCT_IMAGES: '/products/image',
  PRODUCT_VARIANTS: '/product-variants', // Added Product Variants endpoint
  LOGIN: '/auth/login',
  LOGOUT: '/auth/logout',
  CHECK_AUTH: '/auth/me',
};
