import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import DashboardWrapper from "./dashboardWrapper";
import { Toaster } from "@/components/ui/toaster";
// import LoginPage from "./login/page";
// import { AuthProvider } from "@/contexts/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <AuthProvider> */}
        <DashboardWrapper>
          {children}
          <Toaster />
        </DashboardWrapper>
        {/* </AuthProvider> */}
      </body>
    </html>
  );
}
